name: Push2EC2

run-name: ${{github.actor}} deploy to ec2

on:
  push:
    branches: main

jobs:  
  deploy:
    name: Deply | Push Backend-img to DockerHub
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      - name: Cloudflared-Version
        run: cloudflared --version

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USER}}
          proxy_host: ${{ secrets.EC2_HOST }}
          proxy_username: "cloudflared" 
          proxy_key: |
            cloudflared access ssh --hostname ${{ secrets.EC2_HOST }} --header "CF-Access-Client-Id=${{ secrets.AUTH_TOKEN_ID }}" --header "CF-Access-Client-Secret=${{ secrets.AUTH_TOKEN_SECRET }}"
          
          script: |
            mkdir -p ~/contint-ex13
            cd ~/contint-ex13
            echo "Success" > test.txt

              
